name: CD pipeline

on:
  workflow_run:
    workflows: ["CI - stage v1.1"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app

            IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}

            echo "Deploying version: $IMAGE_TAG"

            # Create .env file
            echo "AWS_REGION=${{ secrets.AWS_REGION }}" > .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "S3_BUCKET=${{ secrets.S3_BUCKET }}" >> .env
            echo "S3_KEY=${{ secrets.S3_KEY }}" >> .env
            echo "SAGEMAKER_PIPELINE_NAME=${{ secrets.SAGEMAKER_PIPELINE_NAME }}" >> .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "MOCK_MODE=${{ secrets.MOCK_MODE }}" >> .env
            echo "TOP_N_DEFAULT=${{ secrets.TOP_N_DEFAULT }}" >> .env
            echo "CORS_ORIGINS=${{ secrets.CORS_ORIGINS }}" >> .env

            docker login -u $DOCKER_USERNAME -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

            export IMAGE_TAG=$IMAGE_TAG
            export DOCKER_USERNAME=$DOCKER_USERNAME

            docker compose pull
            docker compose down
            docker compose up -d

            docker image prune -af